### PR TITLE
Adding lazy-load of photos by impementing intersection oberserver

### PR DESCRIPTION
**Pull request by purebase**
- [ ] I have followed the 'Sending a Pull Request' section of the
      [contributing guide](https://github.com/igordanchenko/react-photo-album/blob/main/CONTRIBUTING.md#sending-a-pull-request)

### CODE REVIEW

**Comment by purebase** [comment]
Hello igordanchenko,
the examples is missing a lazy loading of photos. I implemented the intersection observer technic by extending the existing 'custom renderer' example.
Best regards from Germany, Thomas

**Comment by igordanchenko** [comment]
Thank you for sharing. This library already supports lazy loading via the native `loading="lazy"` attribute, which works out-of-the-box.

**Comment by purebase** [comment]
Hello, 

I know that there is the load attribute with const 'lazy'. But in my opinion that is not enough. For lazy loading with good user experience, there should be a loading indicator.

And secondly, a placeholder with the same dimension as the following content, in this case the image. This prevents the elements of the React Photo Album from being only one pixel high and therefore all being loaded immediately - despite the 'lazy' feature.

Using the interception.oberserver is optional, but still useful to make elements disappear again after loading starts.

All in all, I think a practical example makes sense, whether with loading-lazy attributes or with an optional intersection observer. What do you think?

**Comment by igordanchenko** [comment]
> I know that there is the load attribute with const 'lazy'. But in my opinion that is not enough. For lazy loading with good user experience, there should be a loading indicator.

Well, if your goal is to implement a loading indicator, then sure. 

My personal favorite is the blurred-out placeholder in Next.js - https://react-photo-album.com/examples/nextjs

But IMO, `loading="lazy"` should be sufficient for most users, and including an `IntersectionObserver` example would be an overkill.

> And secondly, a placeholder with the same dimension as the following content, in this case the image. This prevents the elements of the React Photo Album from being only one pixel high and therefore all being loaded immediately - despite the 'lazy' feature.

This should never be the case, unless you made a mistake in the custom `renderPhoto`. This library renders images with appropriate `width` / `height` / `aspect-ratio` styles, so what you are describing should not be an issue in the first place.

> All in all, I think a practical example makes sense, whether with loading-lazy attributes or with an optional intersection observer. What do you think?

`loading="lazy"` attribute is enabled by default, so all examples already include lazy loading feature.

**Comment by purebase** [comment]
Ok, mein Bild von guter Benutzerführung ist ein Anderes. Aber die Sache mit dem fehlenden Platzhalter habe ich ausprobiert: Genau bei dem Beispielcode "Custom Renderer" wird vor dem Laden nur die Box in Höhe des Textes aufgespannt. Damit hat jeder Bilderrahmen nur noch ca. 1/4 der Endgröße und insgesamt sind viele Bildrahmen zu früh sichtbar und somit auch zu früh geladen.
Hat man nun gar keinen Text mehr, so bleibt nur noch ein horizontaler Streifen des Bildrahmens - und das Lazy Loading ist komplett ausgeschalten.

**Comment by purebase** [comment]
Mmh, and the thing with the default setting 'loading="lazy"' also behaves differently in my Chrome + Firefox on OSX 14.4.1. All images are loaded immediately (Devtools -> Network), even though half the gallery is still in the invisible area. Scrolling the page does not bring up any further entries in the network view.
Just tested with:
https://react-photo-album.com/examples/rows
https://react-photo-album.com/examples/masonry

It's true that every img tag has the setting ''loading="lazy"'', but unfortunately the browser doesn't care!

**Comment by purebase** [comment]
I just looked at can-i-use. The loading attribute should actually work in current browsers.
https://caniuse.com/mdn-html_elements_img_loading

It may be that my Apple devices are configured strangely (but I don't think so :-). Whatever the case, it always has to work for my customers - especially with their older devices. And the Intersection Observer seems to be the better solution.

**Comment by purebase** [comment]
Now it's already late. For me here in Germany it means “good night”. Where do you live?

**Comment by igordanchenko** [comment]
> Exactly in the example code "Custom Renderer" only the box is opened at the height of the text before loading. This means that each picture frame is only about 1/4 of the final size and overall, many picture frames are visible too early and are therefore loaded too early.
If you no longer have any text at all, all that remains is a horizontal strip of the image frame - and lazy loading is completely switched off.

I'm not exactly sure what kind of issue you experienced, but as I explained before, this should not happen as long as you properly size your images and wrappers. Please feel free to open a discussion with a specific example if you require further assistance.

> Mmh, and the thing with the default setting 'loading="lazy"' also behaves differently in my Chrome + Firefox on OSX 14.4.1. All images are loaded immediately (Devtools -> Network), even though half the gallery is still in the invisible area. Scrolling the page does not bring up any further entries in the network view.

Different browsers use different heuristic algorithms for lazy loading, which may depend on your browser window size and network conditions. It's true that the desktop version of Chrome is particularly pessimistic about prefetching images. You'd need to increase the number of images in the above examples to see that Chrome does not load all images immediately when the page loads. But at the end of the day, that's exactly how `loading="lazy"` is supposed to work. If you require more granular control over lazy loading, you use the right approach with `IntersectionObserver`. But, as I said before, I don't believe this is the right option for most users.

**Comment by purebase** [comment]
Thanks for the offer, but I think I just have different implementation requirements. At this point I would go my own way of design.
Thank you for providing such a cool library!!

**Pull request closed without merging**
